version: "3"
services:
  db:
    container_name: IAmSuperCB-MySQL
    image: mysql:8.0.21
    expose:
      - "3306"
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
